### ISSUE TITLE
Training Step Count

### ISSUE THREAD

**Issue by ekurtulus** [JonasGeiping/cramming#11]
I am asking this for benchmarking purposes. In the config files, it is stated that training lasts 600_000 micro-batch steps and is terminated in 1 day if it does not reach it. How many training steps are actually taken using an RTX-A4000 in a day ?

**Comment by JonasGeiping** [comment]
Let me know if other questions come up!

**Comment by ekurtulus** [comment]
Thank you very much for your answer ! I have another question. The tokenizer used for the trained BERT models are bert-x-cased where x is either base or large, right ?

**Comment by JonasGeiping** [comment]
Hi, do you mean the baseline, pretrained BERT models?

The baseline comparison (e.g. in Table.3, row 1) is to `bert-base-uncased`. If I remember correctly, this was a tiny bit better than `bert-base-cased` in this evaluation.

**Comment by JonasGeiping** [comment]
Closing this for now.
