### ISSUE TITLE
Preprocessed files on S3/Google Drive

### ISSUE THREAD

**Issue by tals** [JonasGeiping/cramming#13]
Hey there, and thank you for this wonderful work!

I'm trying to grab the prepcoessed dataset files from Dropbox, but it is sort of a pain to remotely download it due to Dropbox putting restrictions on the links :\

Would it be possible for you to mirror it on Google Drive (so [gdown](https://github.com/wkentaro/gdown) would work) or on S3 (via [Requester Pays](https://docs.aws.amazon.com/AmazonS3/latest/userguide/RequesterPaysExamples.html))?

**Comment by JonasGeiping** [comment]
Hi, sorry to hear that. I didn't expect the demand for preprocessed data to be more than sporadic, and to overwhelm the dropbox limits.

I don't have a gdrive account large enough to host these files and I've never worked with AWS in any serious capacity to set this up (and requester pays would not be my favorite model).  
What makes most sense for me would be a huggingface datasets upload, but don't have time to set that up at the moment.

**Comment by JonasGeiping** [comment]
This is now very easy with https://github.com/JonasGeiping/cramming/releases/tag/Torch2.1. You can just stream data directly from huggingface.
