### ISSUE TITLE
Can't evaluate

### ISSUE THREAD

**Issue by TahaBinhuraib** [JonasGeiping/cramming#16]
```File "/home/tahabinhuraib/cramming/eval.py", line 23, in main_downstream_process
    tokenizer, cfg_arch, model_file = cramming.utils.find_pretrained_checkpoint(cfg)
  File "/home/tahabinhuraib/cramming/cramming/utils.py", line 177, in find_pretrained_checkpoint
    all_checkpoints = [f for f in os.listdir(local_checkpoint_folder)]
FileNotFoundError: [Errno 2] No such file or directory: '/home/tahabinhuraib/cramming/outputs/bert-finetuning/checkpoints'
```

**Comment by TahaBinhuraib** [comment]
Looking at the outputs, I can't see an outputs/bert-finetuning/checkpoints directory. 
Only an outputs/bert/checkpoints directory

**Comment by JonasGeiping** [comment]
Hi, it's hard to say what is going wrong here without more details. What are the commands you used for pretraining/finetuning? output/bert and outputs/bert-finetuning are both folders that are named based on your command.

**Comment by TahaBinhuraib** [comment]
@JonasGeiping I'm using this command for pretrain: `python pretrain.py name=bert data=bookcorpus-wikipedia arch=bert-original train=bert-original`

**Comment by JonasGeiping** [comment]
Ok, this is helpful, here are a few things to consider:
1) The evaluation checks for a pretraining model with a matching `name`, and then takes the latest checkpoint by default (but this can be changed in the eval settings via `eval.checkpoint=...`). So, `eval.checkpoint` does not control the checkpoint, only the checkpoint settings.
2) If you are evaluating with `dryrun=True`, then evaluation numbers will not be sensible, this is just a test setting.
3) You are pretraining the original bert model with the original bert training recipe. This won't get very far within the default budget setting, and might not break below 6.5 loss.

**Comment by TahaBinhuraib** [comment]
Thank you very much 🙏
