### ISSUE TITLE
Cola dataset evaluation

### ISSUE THREAD

**Issue by TahaBinhuraib** [JonasGeiping/cramming#21]
<img width="750" alt="image" src="https://github.com/JonasGeiping/cramming/assets/69626776/05c0253e-976e-4ad0-83ec-61b7c7b4a1a9">

Hello, when I use the evaluation script I get this for the cola dataset but all looks well for the other datasets. 
Also, when I look at the logs, I can see the Matthews correlation. 
<img width="699" alt="image" src="https://github.com/JonasGeiping/cramming/assets/69626776/6c5b804c-dee6-4df3-88c0-edc154af03f3">

**Comment by JonasGeiping** [comment]
ugh, thanks for letting me know! What version of `evaluate` is this using?

**Comment by JonasGeiping** [comment]
yeah, the metric from the logs is also fine. The .yaml file is just mistyped - somehow a python object is written into the file, instead of a float value. If you figure out what the object class is , then you could probably even reload the number correctly from the yaml file.

**Comment by JonasGeiping** [comment]
Also fixed in https://github.com/JonasGeiping/cramming/releases/tag/Torch2.1
