### ISSUE TITLE
Finetuning for SQuAD task

### ISSUE THREAD

**Issue by kisacats** [JonasGeiping/cramming#35]
Hello,

First of all thank you for your labour for creating this work. I have pretrained crammed bert model with custom data and I want to know is it possible to use it for QA task. I tried register it as modified architecture of ScriptableLMForTokenClassification but I could not. Do you have any suggestion to finetune for QA taskespecially using as HF model?

**Comment by JonasGeiping** [comment]
Declaring it as `AutoModelForTokenClassification` should work. What's the error?

**Comment by kisacats** [comment]
> Declaring it as `AutoModelForTokenClassification` should work. What's the error?

When declared it as AutoModelForTokenClassification it throws AttributeError: 'ScriptableLMForTokenClassification' object has no attribute 'num_labels'. After setting num_labels as two manually, the error becomes RuntimeError: mat1 and mat2 shapes cannot be multiplied (512x768 and 1024x1)
