### ISSUE TITLE
try it on Mac M1 but failed

### ISSUE THREAD

**Issue by yangboz** [JonasGeiping/cramming#36]
after pip install -e .
try
 ```
python pretrain.py name=test arch=hf-bert-base train=bert-base  dryrun=True
```
the console error as following 
```
zsh: illegal hardware instruction  python pretrain.py name=test arch=hf-bert-base train=bert-base  dryrun=True
```
any idea ? thanks.

**Comment by JonasGeiping** [comment]
Uh, that is a mean error message. It is likely unrelated to cramming directly, though. You might have an ARM/x86_64 mismatch on some dependencies (maybe pytorch?). Sorry, this is hard for me to debug at all without acess to an M1 Mac.

**Comment by JonasGeiping** [comment]
Closing this for now. Feel free to re-open if anything comes up
