### ISSUE TITLE
preprocessed c4 dataset?

### ISSUE THREAD

**Issue by w32zhong** [JonasGeiping/cramming#7]
Hi, I am also trying to replicate the preprocessed c4 dataset.
Since the default config has `deduplicate_entries: True`, however, the "dedup tool" seems not found: `cramming/dedup/release/dedup_dataset: not found`.

I am wondering where to get the dedup tool, and if possible, can we download the preprocessed c4 dataset somewhere?

**Comment by w32zhong** [comment]
Thank you so much @JonasGeiping .

**Comment by JonasGeiping** [comment]
For everyone finding this issue later, please check this section: https://github.com/JonasGeiping/cramming#preprocessed-datasets
